LICENSE, README.txt
https://bugzilla.mozilla.org/show_bug.cgi?id=1174909
=> Add README and LICENSE

extension/content/customPersonaEditor.js, extension/content/personas.js, extension/content/preferences.js, extension/install.rdf, extension/modules/Observers.js, extension/modules/Preferences.js, extension/modules/StringBundle.js, extension/modules/log4moz.js, extension/modules/service.js
=> Add compatibility to Firefox 45

extension/content/customPersonaEditor.js
Custom Persona Data:URI Bug Fix
=> Custom Persona Data:URI Bug Fix

extension/modules/personas.js
=> Follow-up of restartless change

extension/modules/personas.js
=> Remove Survey Code

extension/modules/service.js
Cookie-Changed Observer Removed
=> Remove Cookie-Changed Observer

extension/bootstrap.js, extension/modules/personas.js
Fix for Reinstalling the Personas Plus add-on will cause display issues
in the menu Bug
=> Reinstalling the Personas Plus add-on will cause display issues in the menu

extension/modules/service.js
Fix for After pressing “Undo” button, the theme is not removed Bug
=> Undo Fix for First Install

extension/modules/service.js
Unhandled promise fix. First checks favourites.json check before
removing it.
=> Unhandled Promise Fixes #56

extension/modules/Observers.js, extension/modules/Preferences.js, extension/modules/StringBundle.js, extension/modules/log4moz.js, extension/modules/personas.js, extension/modules/service.js
Remove deprecated expressions closures. Fixes #55
=> Remove deprecated expressions closures

extension/modules/service.js
"Undo" drop down bar is displayed if "Random selection from Featured"
theme is added. Fixes #53
=> Undo Drop down bar for "Random selection from Featured"

extension/modules/service.js
Installing a theme from Random Selection From Featured adds the theme to My Recently Selected. Fixes #39
=> Installing a theme from Random Selection From Featured adds the theme to My Recently Selected

extension/bootstrap.js
When PP is disabled or uninstalled, a confirmation box will ask user to
remove the active theme or not.
When uninstall takes place, if the active theme is Groovy Blue, it will
be removed automatically.
Fixes #50
=> Handle Theme for Disable and Uninstall

extension/content/customPersonaEditor.js, extension/content/customPersonaEditor.xul
This will let users to have advanced operating system colour picker via
html5 input color element, when creating Custom Persona
=> Advanced Color Picker for Custom Persona

extension/content/preferences.xul, extension/defaults/preferences/prefs.js, extension/modules/personas.js, extension/modules/service.js
Remove useTextColor and useAccentColor Preferences from preferences
files and remove any related code from JS files.
Fixes #59
=> Remove useTextColor and useAccentColor Preferences

extension/defaults/preferences/prefs.js, extension/modules/personas.js
perWindow hacks around LightweightThemeManager and is bound to break.
Fixes #60
=> Remove perWindow Support

extension/bootstrap.js
=> Fix removal of 'Groovy Blue' theme

extension/content/customPersonaEditor.js
Custom persona with wrong image size is applied anyway
Fixes #72
=> Custom persona with wrong image size is applied anyway

extension/bootstrap.js
This commit fixes the toolbar button issue for Mac OS X Thunderbird
=> Thunderbird Fix for Mac OS X

extension/modules/Preferences.js
This removed remnant deprecated Expression Closure. Fixes #85
=> Remove Deprecated Expression Closure

extension/content/customPersonaEditor.js, extension/defaults/preferences/prefs.js
This adds a preference to disable image dimension restriction for
custom personas. Fixes #94
=> Disabling Image Size Restriction
